site_name: "{{cookiecutter.project_name}}"
site_description: "Documentation website for {{cookiecutter.project_name}}"
site_author: "{{cookiecutter.author_given_names}} {{cookiecutter.author_family_names}}"
copyright: "© {% now 'utc', '%Y' %}, {{cookiecutter.author_given_names}} {{cookiecutter.author_family_names}}"
repo_url: "https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}/"
repo_name: "{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}"

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github

nav:
  - index.md
  - api.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          docstring_style: google
          import:
            - "https://docs.python.org/3/objects.inv"
          paths: [src]
