[tool.codespell]
skip = '*.lock'

[tool.pytest.ini_options]
addopts = "--color=yes -vv"
testpaths = [
    "tests",
]

[tool.ruff]
fix = true
force-exclude = true
ignore = [
    "D203", # no-blank-line-before-class
    "D212", # multi-line-summary-first-line
    "D407", # removed dashes lines under sections
    "D417", # argument description in docstring (unreliable)
    'COM812', # ruff-format recommended
    'COM819', # ruff-format recommended
    'D206', # ruff-format recommended
    'E501', # ruff-format recommended
    'ISC001', # ruff-format recommended
    'Q000', # ruff-format recommended
    'Q001', # ruff-format recommended
    'Q002', # ruff-format recommended
    'Q003', # ruff-format recommended
    'W191', # ruff-format recommended
]
per-file-ignores = {"post_gen_project.py" = [
    "T201",
], "test_*" = [
    "S101",
]}
select = [
    "A",
    "ARG",
    "B",
    "BLE",
    "C",
    "COM",
    "D",
    "DJ",
    "DTZ",
    "E",
    "EM",
    "ERA",
    "EXE",
    "F",
    "FBT",
    "I",
    "ICN",
    "ISC",
    "N",
    "NPY",
    "PD",
    "PGH",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "T",
    "TCH",
    "TID",
    "UP",
    "W",
    "YTT",
]
target-version = "py39"
mccabe.max-complexity = 18

[tool.tomlsort]
all = true
spaces_indent_inline_array = 4
trailing_comma_inline_array = true
overrides."project.classifiers".inline_arrays = false
overrides."tool.coverage.paths.source".inline_arrays = false

[tool.tox]
legacy_tox_ini = """
    [gh-actions]
    python =
        3.9: py39
        3.10: py310
        3.11: py311
        3.12: py312

    [gh-actions:env]
    OS =
        ubuntu-latest: linux
        macos-latest: macos
        windows-latest: windows

    [testenv]
    skip_install = true
    description =
        Test package creation
    deps =
        cookiecutter
        pytest
    commands =
        pytest {posargs}

    [tox]
    env_list = py3{9,10,11,12}-{linux,macos,windows}
"""
