---
extends: substitution
message: Use the British spelling '%s' instead of the US '%s'.
level: error
ignorecase: true
swap:
  # -our vs. -or
  ardor: ardour
  candor: candour
  color: colour
  demeanor: demeanour
  endeavor: endeavour
  favour: favour
  fervor: fervour
  flavor: flavour
  harbor: harbour
  honor: honour
  humor: humour
  labor: labour
  neighbor: neighbour
  odor: odour
  pavor: pavour
  rancor: rancour
  rigor: rigour
  rumor: rumour
  savor: savour
  splendor: splendour
  succor: succour
  valour: valour
  vapor: vapour
  vigor: vigour
  # and their derivatives
  colored: coloured
  coloring: colouring
  colors: colours
  endeavored: endeavoured
  endeavoring: endeavouring
  flavored: flavoured
  flavoring: flavouring
  honored: honoured
  honoring: honouring
  honors: honours
  humors: humours
  labored: laboured
  laboring: labouring
  labors: labours
  neighbors: neighbours
  rumors: rumours
  splendors: splendours
  # -re vs. -er
  caliber: calibre
  center: centre
  fiber: fibre
  luster: lustre
  meager: meagre
  meter: metre
  saber: sabre
  saltpeter: saltpetre
  sepulcher: sepulchre
  theater: theatre
  # and their derivatives
  calibers: calibres
  centers: centres
  fibers: fibres
  lusters: lustres
  meters: metres
  theaters: theatres
  # -ise vs. -ize
  '(\w+)ization\b': "$1isation"
  '(\w+)ize\b': "$1ise"
  '(\w+)ized\b': "$1ised"
  '(\w+)izing\b': "$1ising"
  # add other common forms:
  '(\w+)izable\b': "$1isable"
  # -yse vs. -yze
  '(\w+)yze\b': "$1yse"
  '(\w+)yzed\b': "$1ysed"
  '(\w+)yzing\b': "$1ysing"
  # double L vs. Single L
  distill: distil
  enroll: enrol
  enrollment: enrolment
  enthrall: enthral
  fulfill: fulfil
  initialed: initialled
  initialing: initialling
  instill: instil
  labeled: labelled
  labeling: labelling
  libelous: libellous
  modeling: modelling
  signaling: signalling
  traveler: traveller
  traveling: travelling
  traveled: travelled
  # -ogue vs. -og
  analog: analogue
  catalog: catalogue
  demagog: demagogue
  dialog: dialogue
  monolog: monologue
  pedagog: pedagogue
  prolog: prologue
  # ae/oe vs. e
  airplane: aeroplane
  anemia: anaemia
  anesthesia: anaesthesia
  encyclopedia: encyclopaedia
  eon: aeon
  fetus: foetus
  pediatric: paediatric
  # -ce vs. -se
  defense: defence
  license: licence
  offense: offence
  pretense: pretence
  # miscellaneous specific words
  aging: ageing
  aluminum: aluminium
  authorizer: authoriser
  buses: busses
  cipher: cypher
  cozy: cosy
  dependent: dependant
  draft: draught
  furor: furore
  gray: grey
  inquiry: enquiry
  jail: gaol
  jewelry: jewellery
  likable: likeable
  livable: liveable
  maneuver: manoeuvre
  marvelous: marvellous
  matte: matt
  mustache: moustache
  pajamas: pyjamas
  plow: plough
  programme: program
  ratable: rateable
  reconnoiter: reconnoitre
  sizable: sizeable
  skillful: skilful
  smolder: smoulder
  somber: sombre
  specialty: speciality
  specter: spectre
  sulfur: sulphur
  unshakable: unshakeable
  willful: wilful
  yogurt: yoghurt
