extends: existence
message: "Don't put a space before or after a dash."
link: "https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#dashes"
nonword: true
level: warning
action:
  name: edit
  params:
    - remove
    - " "
tokens:
  - '\s[—–]\s'
