extends: existence
message: >-
  Avoid en dashes ('–'). For hyphenated words, use a hyphen ('-').\nFor
  parenthesis, use an em dash ('—').
nonword: true
level: error
action:
  name: edit
  params:
    - replace
    - "-"
    - "—"
tokens:
  - "–"
