---
name: Question
description: General Questions About Using the Cookiecutter Template
labels:
  - question
body:
  - id: topic
    type: dropdown
    attributes:
      label: What is the Topic of Your Question
      description: Please indicate the topic in the title of your question.
      options:
        - Documentation
        - Installation
        - Usage
        - Website
        - Other
    validations:
      required: true
  - id: question
    type: textarea
    attributes:
      label: Add Your Question Below
    validations:
      required: true
