---
name: Task
description: A Task to be Completed
labels:
  - task
body:
  - id: section
    type: textarea
    attributes:
      label: What needs to be done?
      description: Please give as much detail as possible.
    validations:
      required: true
